services:
  #  bikeshop:
  #    image: bikeshop
  #    build:
  #      context: .
  #      dockerfile: Dockerfile

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    privileged: true
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"

  
